//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Msgpack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevToysMsgpackResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevToysMsgpackResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Msgpack.DevToysMsgpackResources", typeof(DevToysMsgpackResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode and decode MessagePack (in Base64 and HEX) to and from JSON.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        internal static string ConversionTitle {
            get {
                return ResourceManager.GetString("ConversionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash.
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode and decode MessagePack (in Base64 and HEX) to and from JSON.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Spaces.
        /// </summary>
        internal static string FourSpaces {
            get {
                return ResourceManager.GetString("FourSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For JSON formatting.
        /// </summary>
        internal static string IndentationDescription {
            get {
                return ResourceManager.GetString("IndentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        internal static string IndentationTitle {
            get {
                return ResourceManager.GetString("IndentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid Base64&gt;.
        /// </summary>
        internal static string InvalidBase64 {
            get {
                return ResourceManager.GetString("InvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid Exception&gt;.
        /// </summary>
        internal static string InvalidException {
            get {
                return ResourceManager.GetString("InvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid HEX String&gt;.
        /// </summary>
        internal static string InvalidHex {
            get {
                return ResourceManager.GetString("InvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid JSON&gt;.
        /// </summary>
        internal static string InvalidJson {
            get {
                return ResourceManager.GetString("InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON to Msgpack Base64.
        /// </summary>
        internal static string JsonToMsgpackBase64 {
            get {
                return ResourceManager.GetString("JsonToMsgpackBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON to Msgpack HEX.
        /// </summary>
        internal static string JsonToMsgpackHex {
            get {
                return ResourceManager.GetString("JsonToMsgpackHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msgpack JSON Encoder / Decoder.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minified.
        /// </summary>
        internal static string Minified {
            get {
                return ResourceManager.GetString("Minified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msgpack Base64 to JSON.
        /// </summary>
        internal static string MsgpackBase64ToJson {
            get {
                return ResourceManager.GetString("MsgpackBase64ToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msgpack HEX to JSON.
        /// </summary>
        internal static string MsgpackHexToJson {
            get {
                return ResourceManager.GetString("MsgpackHexToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Tab.
        /// </summary>
        internal static string OneTab {
            get {
                return ResourceManager.GetString("OneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For HEX string formatting.
        /// </summary>
        internal static string SeparatorDescription {
            get {
                return ResourceManager.GetString("SeparatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string SeparatorTitle {
            get {
                return ResourceManager.GetString("SeparatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msgpack &lt;&gt; JSON.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Spaces.
        /// </summary>
        internal static string TwoSpaces {
            get {
                return ResourceManager.GetString("TwoSpaces", resourceCulture);
            }
        }
    }
}
