on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/main
        run: git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION} ./DevToys.Msgpack.sln
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build ./DevToys.Msgpack.sln
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . ./DevToys.Msgpack.sln
      - name: Push
        run: dotnet nuget push DevToys.Msgpack.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET} --skip-duplicate
        env:
          NUGET: ${{ secrets.NUGET }}
